swagger: "2.0"
info: 
  version: "0.0.1"
  title: "cone classifier"
  description: "classify cones from csv data"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Ryan Danehy and Brandon Fischer"
  license: 
    name: "Apache"
host: "localhost:4555"

consumes:
  - "text/html"
produces:
  - "text/html"

basePath: "/app"

paths:
  /run:
    get:
      operationId: scripts.uploadrun.display
      description: "Displays upload file page"
      responses:
        "200":
          description: "Upload page displayed successfully"

  /upload_file:
    post:
      operationId: scripts.uploadrun.upload
      description: "Generate post request to actually upload file"
      responses:
        "201":
          description: "File upload successful"

  /retrain:
    get:
      operationId: scripts.uploadrerun.display
      description: "Displays upload new training file page"
      responses:
        "200":
          description: "Upload page displayed successfully"

  /upload_file_retrain:
    post:
      operationId: scripts.uploadrerun.upload
      description: "Generate post request to actually upload file"
      responses:
        "201":
          description: "File upload successful"
          
  
