swagger: "2.0"
info: 
  version: "0.0.1"
  title: "cone classifier"
  description: "classify cones from csv data"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Ryan Danehy and Brandon Fischer"
  license: 
    name: "Apache"
host: "localhost:4555"

consumes:
  - "text/html"
produces:
  - "text/html"

basePath: "/app"

paths:
  /upload:
    get:
      operationId: upload.display
      description: "Displays upload file page"
      responses:
        "200":
          description: "Upload page displayed successfully"

  /upload_file:
    post:
      operationId: upload.upload
      description: "Generate post request to actually upload file"
      responses:
        "201":
          description: "File upload successful"
          
  
